server:
  port: 9876

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pathologylab
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /
      suffix: .jsp